apiVersion: apps/v1
kind: Deployment
metadata:
    name: skaffold-kaniko-test
spec:
    selector:
        matchLabels:
            app: skaffold-kaniko-test
    template:
        metadata:
            labels:
                app: skaffold-kaniko-test
        spec:
            containers:
                - name: app
                  image: docker.my.private.registry/middleware/test
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                          name: config-skaffold-test
            imagePullSecrets:
                - name: private
