apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - deployment.yaml
configMapGenerator:
    - name: config-skaffold-test
      literals:
        - TEST_INT=1234
        - TEST_STRING="a fun string;<>?:"

