apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - deplyoment.yaml
configMapGenerator:
    - name: config-middleware-test
      literals:
        - TEST_INT=1234
        - TEST_STRING="a fun string;<>?:"

