apiVersion: apps/v1
kind: Deployment
metadata:
    name: middleware-test
spec:
    template:
        spec:
            containers:
                - name: app
                  args:
                      - nodemon
                      - --inspect
                      - server.js

