apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../base
patchStrategicMerge:
    - debugging.yaml
configMapGenerator:
    - name: config-middleware-test
      behavior: merge
      literals:
          - TEST_STRING="next level weird string;agreag>P{}"

